export const PRODUCT_LIST_REQUEST = 'PRODUCT_FILE_LOAD'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_FILE_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_FILE_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_LOAD'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'